# Generated by Django 3.1.3 on 2020-12-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
    ]
