# Generated by Django 3.1.3 on 2020-12-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20201201_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
